# Generated by Django 4.1.3 on 2022-11-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
