# Generated by Django 4.1.3 on 2022-11-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_customusers_address_alter_customusers_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
