# Generated by Django 4.1.3 on 2022-11-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_customusers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
